---
- hosts: prod1-server
  become: true
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy insureme application
    command: sudo docker run -itd -p 8084:8081  shabana4195/banking:1.0
